# Generated by Django 4.2 on 2025-11-19 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_staffid_user_alter_staffid_role'),
        ('opd', '0003_alter_patient_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission_reason', models.TextField()),
                ('initial_diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='accounts.staffid')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('general', 'General Ward'), ('private', 'Private Room'), ('icu', 'ICU'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffid')),
                ('admitted_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='admission.admittedpatient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prescription_reference', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffid')),
                ('admitted_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_charges', to='admission.admittedpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='admission.room')),
            ],
            options={
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='admittedpatient',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.bed'),
        ),
        migrations.AddField(
            model_name='admittedpatient',
            name='opd_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='opd.patient'),
        ),
        migrations.AddField(
            model_name='admittedpatient',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='admission.room'),
        ),
    ]
