# Generated by Django 4.2 on 2026-01-18 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('original_bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('return_reason', models.CharField(choices=[('wrong_medicine', 'Wrong Medicine Given'), ('expired', 'Expired Medicine'), ('damaged', 'Damaged Package'), ('allergy', 'Patient Allergy'), ('doctor_changed', 'Doctor Changed Prescription'), ('extra', 'Extra Medicine (Not Needed)'), ('other', 'Other Reason')], default='other', max_length=50)),
                ('return_reason_detail', models.TextField(blank=True, null=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Medicine Return',
                'verbose_name_plural': 'Medicine Returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('patient_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(default='Walk-in Customer', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_direct_sale', models.BooleanField(default=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pharmacy Sale',
                'verbose_name_plural': 'Pharmacy Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_id', models.UUIDField(blank=True, null=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine_form', models.CharField(default='tablet', max_length=50)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacysale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.CreateModel(
            name='MedicineReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_id', models.UUIDField(blank=True, null=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity_returned', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine_form', models.CharField(default='tablet', max_length=50)),
                ('stock_restored', models.BooleanField(default=False)),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.medicinereturn')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
        migrations.AddField(
            model_name='medicinereturn',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='pharmacy.pharmacysale'),
        ),
    ]
