# Generated by Django 4.2 on 2025-09-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffid',
            name='user',
        ),
        migrations.AlterField(
            model_name='staffid',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
    ]
