# Generated by Django 4.2 on 2026-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_staffid_user_alter_staffid_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffid',
            name='password',
            field=models.CharField(default='1234', help_text='Password for sidebar menu access', max_length=100),
        ),
    ]
