# Generated by Django 4.2 on 2025-10-20 21:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('products_in_box', models.PositiveIntegerField(default=1, help_text='How many product-units in this entry (usually 1 box)')),
                ('items_per_product', models.PositiveIntegerField(default=1, help_text='How many items (eg packs) are inside one product unit (box)')),
                ('subitems_per_item', models.PositiveIntegerField(default=1, help_text='How many sub-items (eg tablets) in each item')),
                ('weight_or_quantity', models.CharField(blank=True, help_text='Optional textual description of weight/volume/quantity', max_length=100, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Purchase price for the product unit (usually a box)', max_digits=18)),
                ('purchase_price_per_item', models.DecimalField(decimal_places=6, default=Decimal('0.0'), editable=False, max_digits=18)),
                ('purchase_price_per_subitem', models.DecimalField(decimal_places=6, default=Decimal('0.0'), editable=False, max_digits=18)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=6, help_text='Sale price for product unit', max_digits=18, null=True)),
                ('sale_price_per_item', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('sale_price_per_subitem', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('purchase_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected margin percent to compute sale prices if sale prices not given', max_digits=6)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percent to apply at sale time (informational)', max_digits=6)),
                ('rack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inventory_receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('batch_no', models.CharField(blank=True, max_length=200, null=True)),
                ('total_boxes', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('total_items', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('total_subitems', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('SALE', 'Sale'), ('PUR', 'Purchase')], max_length=4)),
                ('quantity_boxes', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_items', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_subitems', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_boxes_out', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_items_out', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_subitems_out', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('unit_purchase_price', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Purchase price per product-unit at this transaction', max_digits=18)),
                ('unit_sale_price', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Sale price per product-unit at this transaction', max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
        ),
    ]
