# Generated by Django 4.2 on 2025-11-01 16:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief description of expense', max_length=255)),
                ('category', models.CharField(choices=[('UTILITIES', 'Utilities (Electric, Water, Gas)'), ('SALARIES', 'Staff Salaries'), ('SUPPLIES', 'Office Supplies'), ('MAINTENANCE', 'Maintenance & Repairs'), ('FOOD', 'Tea/Coffee/Food'), ('TRANSPORT', 'Transportation'), ('RENT', 'Rent'), ('MARKETING', 'Marketing & Advertising'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in PKR', max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date of expense')),
                ('notes', models.TextField(blank=True, help_text='Additional details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
