# Generated by Django 4.2 on 2025-11-17 09:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Distributor/Supplier name', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Complete address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Medicine distributor/supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.distributor'),
        ),
    ]
