# Generated by Django 4.2 on 2025-11-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_distributor_product_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributor',
            field=models.CharField(blank=True, help_text='Medicine distributor/supplier name', max_length=255, null=True),
        ),
    ]
