# Generated by Django 4.2 on 2025-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medicine_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('drops', 'Drops'), ('ointment', 'Ointment/Cream'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('other', 'Other')], default='tablet', help_text='Form of medicine (tablet, syrup, injection, etc.)', max_length=20),
        ),
    ]
