# Generated by Django 4.2 on 2025-12-25 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_medicine_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage provided by distributor on purchase', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor_discount_pkr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount in PKR provided by distributor', max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='net_purchase_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Purchase price after distributor discount', max_digits=18),
        ),
    ]
