# Generated by Django 4.2 on 2026-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_distributor_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('SALE', 'Sale'), ('PUR', 'Purchase'), ('RET', 'Return')], max_length=4),
        ),
    ]
