# Generated by Django 4.2 on 2026-01-20 21:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorytransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, help_text='Batch number from manufacturer', max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of this batch', null=True)),
                ('quantity_packs', models.PositiveIntegerField(default=1, help_text='Number of packs in this batch')),
                ('quantity_items', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Total items (strips) in this batch', max_digits=18)),
                ('quantity_subitems', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Total subitems (tablets) in this batch', max_digits=18)),
                ('current_packs', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Current packs remaining', max_digits=18)),
                ('current_items', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Current items remaining', max_digits=18)),
                ('current_subitems', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Current subitems remaining', max_digits=18)),
                ('purchase_price_per_pack', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('sale_price_per_pack', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('distributor_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('distributor_discount_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_purchase_price_per_pack', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Date this batch was received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this batch is available for sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.productbatch'),
        ),
    ]
