# Generated by Django 4.2 on 2026-01-20 22:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productbatch_inventorytransaction_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid to this distributor', max_digits=18),
        ),
        migrations.AddField(
            model_name='distributor',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total purchase amount from this distributor', max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor_ref',
            field=models.ForeignKey(blank=True, help_text='Link to distributor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.distributor'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Distributor for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.distributor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='distributor',
            field=models.CharField(blank=True, help_text='Medicine distributor/supplier name (legacy)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DistributorPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, help_text='Distributor invoice number', max_length=100, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.distributor')),
            ],
            options={
                'verbose_name': 'Distributor Purchase',
                'verbose_name_plural': 'Distributor Purchases',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=18)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of payment')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='Cheque/Transaction reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.distributor')),
            ],
            options={
                'verbose_name': 'Distributor Payment',
                'verbose_name_plural': 'Distributor Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productbatch',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text='Purchase invoice for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.distributorpurchase'),
        ),
    ]
