# Generated by Django 4.2 on 2026-01-24 14:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_distributor_total_paid_distributor_total_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributor_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage provided by distributor on purchase', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='distributor_discount_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Discount amount in PKR provided by distributor', max_digits=18),
        ),
    ]
