# Generated by Django 4.2 on 2026-01-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_distributor_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['weight_or_quantity'], name='inventory_p_weight__04f0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['batch_no'], name='inventory_p_batch_n_55ebdb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['total_boxes'], name='inventory_p_total_b_ae7e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
    ]
