# Generated by Django 4.2 on 2025-09-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_staffid_user_alter_staffid_role'),
        ('opd', '0002_patient_delete_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to='accounts.staffid'),
        ),
    ]
