# Generated by Django 4.2 on 2025-12-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_patient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='queue_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('with_doctor', 'With Doctor'), ('checked', 'Checked'), ('none', 'Not in Queue')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
