# Generated by Django 4.2 on 2025-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_add_queue_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Age in months (0-11)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True),
        ),
    ]
