# Generated by Django 4.2 on 2025-12-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_remove_patient_age_patient_age_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacy_queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_queue_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Medicine'), ('dispensing', 'Dispensing'), ('completed', 'Completed'), ('none', 'Not in Pharmacy Queue')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
