# Generated by Django 4.2 on 2026-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_patient_pharmacy_queue_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Age in days (0-30)', null=True),
        ),
    ]
