# Generated by Django 4.2 on 2025-11-08 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_expense'),
        ('opd', '0003_alter_patient_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.IntegerField(default=1, help_text='Number of days')),
                ('morning', models.BooleanField(default=False, help_text='Take in morning')),
                ('evening', models.BooleanField(default=False, help_text='Take in evening')),
                ('night', models.BooleanField(default=False, help_text='Take at night')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='inventory.product')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='opd.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
