# Generated by Django 4.2 on 2025-11-10 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_expense'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (e.g., Headache, Stomach Pain)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of when to use this template', null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplateMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.IntegerField(default=1, help_text='Number of days')),
                ('morning', models.BooleanField(default=False, help_text='Take in morning')),
                ('evening', models.BooleanField(default=False, help_text='Take in evening')),
                ('night', models.BooleanField(default=False, help_text='Take at night')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='doctor.prescriptiontemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
