# Generated by Django 4.2 on 2025-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_prescriptiontemplate_prescriptiontemplatemedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='batch_id',
            field=models.UUIDField(blank=True, help_text='Groups prescriptions issued together in one session', null=True),
        ),
    ]
