# Generated by Django 4.2 on 2025-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_prescription_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, help_text='When the prescription was dispensed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False, help_text='Whether this prescription has been dispensed to patient'),
        ),
    ]
