# Generated by Django 4.2 on 2025-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_prescription_dispensed_at_prescription_is_dispensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='development',
            field=models.TextField(blank=True, help_text='Development section', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='investigation_advised',
            field=models.TextField(blank=True, help_text='Investigation advised section', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='medical_examination',
            field=models.TextField(blank=True, help_text='Medical examination findings section', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='presenting_complaints',
            field=models.TextField(blank=True, help_text='Presenting complaints section', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, help_text='Provisional diagnosis section', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='vaccination',
            field=models.TextField(blank=True, help_text='Vaccination section', null=True),
        ),
    ]
