# Generated by Django 4.2 on 2026-01-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_prescriptiontemplate_development_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('OD', 'OD - Once daily (روزانہ ایک بار)'), ('BD', 'BD - Twice daily (دن میں دو بار)'), ('TDS', 'TDS - Three times daily (دن میں تین بار)'), ('QID', 'QID - Four times daily (دن میں چار بار)'), ('HS', 'HS - At bedtime (سوتے وقت)'), ('QAM', 'QAM - Every morning (ہر صبح)'), ('QPM', 'QPM - Every evening (ہر شام)'), ('SOS', 'SOS - When required (ضرورت کے وقت)'), ('STAT', 'STAT - Immediately (فوراً)'), ('QOD', 'QOD - Alternate day (ایک دن چھوڑ کر)'), ('QW', 'QW - Once weekly (ہفتے میں ایک بار)'), ('Q6H', 'Q6H - Every 6 hours (ہر 6 گھنٹے)'), ('Q8H', 'Q8H - Every 8 hours (ہر 8 گھنٹے)'), ('AC', 'AC - Before meals (کھانے سے پہلے)'), ('PC', 'PC - After meals (کھانے کے بعد)')], default='OD', help_text='Dosage frequency', max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptiontemplatemedicine',
            name='frequency',
            field=models.CharField(choices=[('OD', 'OD - Once daily (روزانہ ایک بار)'), ('BD', 'BD - Twice daily (دن میں دو بار)'), ('TDS', 'TDS - Three times daily (دن میں تین بار)'), ('QID', 'QID - Four times daily (دن میں چار بار)'), ('HS', 'HS - At bedtime (سوتے وقت)'), ('QAM', 'QAM - Every morning (ہر صبح)'), ('QPM', 'QPM - Every evening (ہر شام)'), ('SOS', 'SOS - When required (ضرورت کے وقت)'), ('STAT', 'STAT - Immediately (فوراً)'), ('QOD', 'QOD - Alternate day (ایک دن چھوڑ کر)'), ('QW', 'QW - Once weekly (ہفتے میں ایک بار)'), ('Q6H', 'Q6H - Every 6 hours (ہر 6 گھنٹے)'), ('Q8H', 'Q8H - Every 8 hours (ہر 8 گھنٹے)'), ('AC', 'AC - Before meals (کھانے سے پہلے)'), ('PC', 'PC - After meals (کھانے کے بعد)')], default='OD', help_text='Dosage frequency', max_length=10),
        ),
    ]
