# Generated by Django 4.2 on 2026-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_add_frequency_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage_form',
            field=models.CharField(choices=[('MG', 'MG'), ('CC', 'CC'), ('ML', 'ML'), ('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules'), ('DROPS', 'Drops'), ('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('SACHET', 'Sachet'), ('PUFF', 'Puff'), ('UNIT', 'Unit')], default='MG', help_text='Dosage form', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='qty',
            field=models.IntegerField(default=1, help_text='Quantity'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplatemedicine',
            name='dosage_form',
            field=models.CharField(choices=[('MG', 'MG'), ('CC', 'CC'), ('ML', 'ML'), ('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules'), ('DROPS', 'Drops'), ('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('SACHET', 'Sachet'), ('PUFF', 'Puff'), ('UNIT', 'Unit')], default='MG', help_text='Dosage form', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptiontemplatemedicine',
            name='qty',
            field=models.IntegerField(default=1, help_text='Quantity'),
        ),
    ]
