# Generated by Django 4.2 on 2026-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_prescription_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiontemplatemedicine',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity (can be decimal like 2.5)', max_digits=8),
        ),
    ]
