# Generated by Django 4.2 on 2026-01-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_prescriptiontemplatemedicine_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='development',
            field=models.TextField(blank=True, help_text='Development section', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='investigation_advised',
            field=models.TextField(blank=True, help_text='Investigation advised section', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_examination',
            field=models.TextField(blank=True, help_text='Medical examination findings section', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='presenting_complaints',
            field=models.TextField(blank=True, help_text='Presenting complaints section', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, help_text='Provisional diagnosis section', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='vaccination',
            field=models.TextField(blank=True, help_text='Vaccination section', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional instructions / Special note', null=True),
        ),
    ]
